version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: cadastro-desenvolvedores-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cadastro-desenvolvedores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: cadastro-desenvolvedores-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_NAME: cadastro-devs
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: cadastro-desenvolvedores-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev

volumes:
  postgres-data:
